### ISSUE TITLE
ClassName is not forwarded on the wrapping <div/>

### ISSUE THREAD

**Issue by arcanis** [ProjectSeptemberInc/gl-react-dom#8] opened 2016-09-03 10:47 UTC
It makes it quite harder to change the style of the element, especially its `display` property (in my use case, I'd need it to be `display: inline-block` instead of `block`).

**Comment by arcanis** [comment] 2016-09-03 10:49
A workaround seems to use the `style` prop instead, but it's a bit unexpected that `className` and `style` each apply on two different elements!

**Comment by gre** [comment] 2016-09-03 10:50
I think you can use

<Surface style={{display:"inline-block"}}

**Comment by gre** [comment] 2016-09-03 10:52
className is not supported by surface , if it is it's mostly accidental.
There is a ...props somewhere. probably should change to explicit pass-in

**Comment by gre** [comment] 2016-09-03 11:06
you pointed at an important point there, there is too much ambiguity in the extra props passed to Surface as well as how `style` works, this will have to be fixed in the future. for now you should use `style` for setting the top level element created by `Surface`, all other children of Surface should  remain a black box for you and is implementation specific.

**Closed by gre** 2016-09-03 11:06 UTC

**Comment by arcanis** [comment] 2016-09-03 11:18
I see, thanks. However, why isn't `className` supported on the top surface element?

**Comment by gre** [comment] 2016-09-03 11:39
I'm wondering why I didn't make `display: inline-block` the default actually !
the idea is you shouldn't have to style anything inside Surface. even the top surface element shouldn't be stylable ideally. It's just convenient that it's supported, but technically you could wrap Surface yourself to do any styling.
The problem is if people assume we can style Surface, then they will start do forbidden style like padding, that will break gl-react assumption and create unexpected bugs.
